/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ceres;

import ceres.crawler.PoemFetcher;
import com.ea.async.Async;

public class App  {
    public static void main(String[] args) {
        Async.init();
        var poemFetcher = new PoemFetcher("https://www.thivien.net","Lý Bạch");
    }
}
