/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ceres;

import ceres.crawler.PoemFetcher;
import com.google.inject.Guice;
import java.io.IOException;

public class App {
    public static void main(String[] args) throws IOException {
        var injector = Guice.createInjector(new AppModule());
        var poemFetcher = injector.getInstance(PoemFetcher.class);
        poemFetcher.fetchPoems();
    }
}
