/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ceres;

import ceres.configuration.ApplicationConfiguration;
import ceres.crawler.PoemFetcher;
import java.io.IOException;

public class App  {
    public static void main(String[] args) throws IOException {
        var config = ApplicationConfiguration.loadFrom("app.yaml");
        var poemFetcher = new PoemFetcher(config.getCrawler().getPoem());
        poemFetcher.fetchPoems()
            .thenApply(poems -> {
                System.out.println(poems);
                return null;
            })
            .exceptionally(ex -> {
                System.out.printf("Failed to fetch poems: %s", ex.getMessage());
                return null;
            });

    }
}
